__mayo__: 'Mayo'
__description__: |
    A deep learning framework with condiment preference as religion.
__version__: 0.0.1
__date__: 14 Aug 2017
__author__: Xitong Gao, Yiren Zhao
__email__: |
    w4DDg8OSw5jDkMKpw5nDhMKNw4LDjsOS
    wpnCgcOiw43DmcKRwpDCn8OIw47DjsKXw43DgsKNw5TDig==
