max_steps: 10000000
batch_size: 64
num_preprocess_threads: 4
num_gpus: 4
moving_average_decay: 0.9999
learning_rate:
    num_epochs_per_decay: 20.0
    initial_learning_rate: 0.001
    learning_rate_decay_factor: 0.16
optimizer:
    type: tensorflow.train.RMSPropOptimizer
    decay: 0.9
    momentum: 0.9
    epsilon: 1.0
